language: objective-c
osx_image: xcode8
xcode_workspace: blank-ios-app.xcworkspace
xcode_scheme: blank-ios-app
xcode_sdk: iphonesimulator

before_install:
  - pod repo update

script:
  - xcodebuild clean build -workspace blank-ios-app.xcworkspace -scheme blank-ios-app -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master